// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pennant.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	pennant.proto

It has these top-level messages:
	FlagRequest
	FlagReply
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

// The request message containing the name of the flag
// and whether it's enabled.
type FlagRequest struct {
	Name    string             `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
	Strings map[string]string  `protobuf:"bytes,2,rep,name=Strings" json:"Strings,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Numbers map[string]float64 `protobuf:"bytes,3,rep,name=Numbers" json:"Numbers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
}

func (m *FlagRequest) Reset()                    { *m = FlagRequest{} }
func (m *FlagRequest) String() string            { return proto1.CompactTextString(m) }
func (*FlagRequest) ProtoMessage()               {}
func (*FlagRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *FlagRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FlagRequest) GetStrings() map[string]string {
	if m != nil {
		return m.Strings
	}
	return nil
}

func (m *FlagRequest) GetNumbers() map[string]float64 {
	if m != nil {
		return m.Numbers
	}
	return nil
}

// The response message containing the flat value
type FlagReply struct {
	Status  int32 `protobuf:"varint,1,opt,name=Status" json:"Status,omitempty"`
	Enabled bool  `protobuf:"varint,2,opt,name=Enabled" json:"Enabled,omitempty"`
}

func (m *FlagReply) Reset()                    { *m = FlagReply{} }
func (m *FlagReply) String() string            { return proto1.CompactTextString(m) }
func (*FlagReply) ProtoMessage()               {}
func (*FlagReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *FlagReply) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *FlagReply) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func init() {
	proto1.RegisterType((*FlagRequest)(nil), "proto.FlagRequest")
	proto1.RegisterType((*FlagReply)(nil), "proto.FlagReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Pennant service

type PennantClient interface {
	// Gets a value for a flag
	GetFlagValue(ctx context.Context, in *FlagRequest, opts ...grpc.CallOption) (*FlagReply, error)
}

type pennantClient struct {
	cc *grpc.ClientConn
}

func NewPennantClient(cc *grpc.ClientConn) PennantClient {
	return &pennantClient{cc}
}

func (c *pennantClient) GetFlagValue(ctx context.Context, in *FlagRequest, opts ...grpc.CallOption) (*FlagReply, error) {
	out := new(FlagReply)
	err := grpc.Invoke(ctx, "/proto.Pennant/GetFlagValue", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Pennant service

type PennantServer interface {
	// Gets a value for a flag
	GetFlagValue(context.Context, *FlagRequest) (*FlagReply, error)
}

func RegisterPennantServer(s *grpc.Server, srv PennantServer) {
	s.RegisterService(&_Pennant_serviceDesc, srv)
}

func _Pennant_GetFlagValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FlagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PennantServer).GetFlagValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Pennant/GetFlagValue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PennantServer).GetFlagValue(ctx, req.(*FlagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Pennant_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Pennant",
	HandlerType: (*PennantServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFlagValue",
			Handler:    _Pennant_GetFlagValue_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pennant.proto",
}

func init() { proto1.RegisterFile("pennant.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 278 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x84, 0x91, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0x4d, 0x62, 0x1a, 0x3b, 0x8d, 0x50, 0x86, 0x22, 0xa1, 0x17, 0x4b, 0x0e, 0xd2, 0x53,
	0x0e, 0x15, 0x44, 0x0b, 0x1e, 0x2c, 0x54, 0x6f, 0x25, 0xa4, 0xe0, 0x7d, 0x53, 0xc7, 0x58, 0xba,
	0xdd, 0xc4, 0x64, 0x23, 0xe4, 0x29, 0x7c, 0x65, 0xd9, 0xcd, 0x06, 0x22, 0x22, 0x3d, 0xed, 0xfc,
	0xc3, 0x7c, 0x1f, 0xb3, 0xbb, 0x70, 0x59, 0x90, 0x10, 0x4c, 0xc8, 0xa8, 0x28, 0x73, 0x99, 0xa3,
	0xab, 0x8f, 0xf0, 0xdb, 0x86, 0xd1, 0x33, 0x67, 0x59, 0x42, 0x9f, 0x35, 0x55, 0x12, 0x11, 0xce,
	0x37, 0xec, 0x48, 0x81, 0x35, 0xb3, 0xe6, 0xc3, 0x44, 0xd7, 0xf8, 0x00, 0xde, 0x56, 0x96, 0x7b,
	0x91, 0x55, 0x81, 0x3d, 0x73, 0xe6, 0xa3, 0xc5, 0x75, 0xeb, 0x88, 0x7a, 0x60, 0x64, 0x26, 0xd6,
	0x42, 0x96, 0x4d, 0xd2, 0xcd, 0x2b, 0x74, 0x53, 0x1f, 0x53, 0x2a, 0xab, 0xc0, 0xf9, 0x17, 0x35,
	0x13, 0x06, 0x35, 0x69, 0xba, 0x04, 0xbf, 0xef, 0xc4, 0x31, 0x38, 0x07, 0x6a, 0xcc, 0x62, 0xaa,
	0xc4, 0x09, 0xb8, 0x5f, 0x8c, 0xd7, 0x14, 0xd8, 0xba, 0xd7, 0x86, 0xa5, 0x7d, 0x6f, 0x29, 0xb6,
	0x2f, 0x3d, 0xc5, 0x5a, 0x3d, 0x36, 0x7c, 0x84, 0x61, 0xbb, 0x5c, 0xc1, 0x1b, 0xbc, 0x82, 0xc1,
	0x56, 0x32, 0x59, 0x57, 0x9a, 0x75, 0x13, 0x93, 0x30, 0x00, 0x6f, 0x2d, 0x58, 0xca, 0xe9, 0x4d,
	0x0b, 0x2e, 0x92, 0x2e, 0x2e, 0x9e, 0xc0, 0x8b, 0xdb, 0x87, 0xc6, 0x3b, 0xf0, 0x5f, 0x48, 0x2a,
	0xd9, 0xab, 0xb2, 0x23, 0xfe, 0xbd, 0xfb, 0x74, 0xfc, 0xab, 0x57, 0xf0, 0x26, 0x3c, 0x5b, 0xdd,
	0xc0, 0x64, 0x9f, 0x47, 0xdd, 0x77, 0xbd, 0x73, 0x96, 0xed, 0x3e, 0x68, 0x77, 0x58, 0xf9, 0x46,
	0x1c, 0x2b, 0x22, 0xb6, 0xd2, 0x81, 0x46, 0x6f, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0xf6, 0xf4,
	0x53, 0xcd, 0xda, 0x01, 0x00, 0x00,
}
